FROM openjdk:latest
WORKDIR /app
COPY target/jsp-servlet-jdbc-mysql-User-Registration-0.0.1-SNAPSHOT.war jsp-servlet-jdbc-mysql-User-Registration-0.0.1-SNAPSHOT.war
EXPOSE 8080
CMD ["java", "-jar", "jsp-servlet-jdbc-mysql-User-Registration-0.0.1-SNAPSHOT.war"]